#!/usr/bin/env python3
"""Leakage-safe retrospective backtest for the ED flow anomaly detector.

The production anomaly ranges are currently generated by fitting an independent vanilla
Prophet model to each hourly metric and using Prophet's nominal central 95% interval as
the anomaly threshold. This research script preserves that model as the control, then
asks whether thresholds calibrated from *previously observed forecast errors* provide
more stable operational alert rates.

Design principles
-----------------
* Match production cadence: fit once each day at a configurable local hour and score the
  next 24 hours.
* No threshold leakage: empirical residual quantiles at time t use only residuals from
  forecasts whose target timestamps are strictly earlier than t.
* Compare training-history windows without changing production code.
* Compare Prophet's upper central-95% bound with an empirical 97.5th-percentile upper
  threshold on an approximately apples-to-apples basis, while retaining 95% warning and
  99% severe candidate thresholds.
* Report alert burden and persistence, not just interval coverage.
* Report historical origin gaps explicitly instead of silently treating them as valid
  backtest days.

This script is research-only. It does not upload or replace anomaly_detection_ranges.csv.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

from staffing_features import parse_hour

FLOW_URL = (
    "https://www.dropbox.com/scl/fi/s83jig4zews1xz7vhezui/"
    "allDataWithCalculatedColumns.csv?rlkey=9mm4zwaugxyj2r4ooyd39y4nl&raw=1"
)

FLOW_TARGETS = (
    "Total_TBS",
    "POD_TBS",
    "Vertical_TBS",
    "TTStr",
    "Overflow",
    "WAITINGADM",
)

TARGET_ALIASES = {
    "Total_TBS": ("Total_TBS", "total_tbs", "TOTAL_TBS"),
    "POD_TBS": ("POD_TBS", "pod_tbs", "Pod_TBS"),
    "Vertical_TBS": (
        "Vertical_TBS",
        "vertical_tbs",
        "VERTICAL_TBS",
        "VERT_TBS",
        "vert_tbs",
    ),
    "TTStr": ("TTStr",),
    "Overflow": ("Overflow", "overflow", "OVERFLOW"),
    "WAITINGADM": ("WAITINGADM",),
}

TOTAL_TBS_COMPONENTS = (
    "TRG_HALLWAY_TBS",
    "POD_GREEN_TBS",
    "POD_YELLOW_TBS",
    "POD_ORANGE_TBS",
    "RAZ_TBS",
    "AMBVERTTBS",
    "QTrack_TBS",
    "Garage_TBS",
)
POD_TBS_COMPONENTS = (
    "TRG_HALLWAY_TBS",
    "POD_GREEN_TBS",
    "POD_YELLOW_TBS",
    "POD_ORANGE_TBS",
)
VERTICAL_TBS_COMPONENTS = ("RAZ_TBS", "AMBVERTTBS", "QTrack_TBS", "Garage_TBS")

DETECTOR_THRESHOLDS = {
    "prophet_nominal_95": "yhat_upper",
    "residual_global_95": "empirical_upper_global_95",
    "residual_global_97_5": "empirical_upper_global_97_5",
    "residual_hour_of_week_95": "empirical_upper_how_95",
    "residual_global_99": "empirical_upper_global_99",
}


@dataclass(frozen=True)
class BacktestConfig:
    evaluation_days: int
    calibration_days: int
    training_windows: tuple[int | None, ...]
    origin_hour: int
    horizon: int
    min_global_samples: int
    min_context_samples: int


def _sum_if_available(frame: pd.DataFrame, columns: Iterable[str]) -> pd.Series | None:
    columns = tuple(columns)
    if not all(column in frame.columns for column in columns):
        return None
    numeric = frame.loc[:, columns].apply(pd.to_numeric, errors="coerce")
    return numeric.sum(axis=1, min_count=len(columns))


def load_flow(url: str = FLOW_URL) -> pd.DataFrame:
    """Load the canonical six flow targets without importing the Chronos stack."""
    raw = pd.read_csv(url)
    if "ds" not in raw.columns:
        raise ValueError("Hourly flow dataset is missing ds")
    raw["ds"] = parse_hour(raw["ds"])
    raw = raw.dropna(subset=["ds"]).sort_values("ds").drop_duplicates("ds", keep="last")

    derived = raw.copy()
    fallback_sums = {
        "Total_TBS": _sum_if_available(derived, TOTAL_TBS_COMPONENTS),
        "POD_TBS": _sum_if_available(derived, POD_TBS_COMPONENTS),
        "Vertical_TBS": _sum_if_available(derived, VERTICAL_TBS_COMPONENTS),
        "Overflow": _sum_if_available(derived, ("POST_POD1", "TRG_HALLWAY1")),
    }

    out = pd.DataFrame({"ds": derived["ds"]})
    for target in FLOW_TARGETS:
        source = next((name for name in TARGET_ALIASES[target] if name in derived.columns), None)
        if source is not None:
            out[target] = pd.to_numeric(derived[source], errors="coerce")
        elif target in fallback_sums and fallback_sums[target] is not None:
            out[target] = fallback_sums[target]
        else:
            raise ValueError(f"Could not resolve required anomaly target {target}")

    return out.sort_values("ds").reset_index(drop=True)


def parse_training_windows(value: str) -> tuple[int | None, ...]:
    windows: list[int | None] = []
    for token in value.split(","):
        token = token.strip().lower()
        if not token:
            continue
        if token in {"all", "full", "none"}:
            window = None
        else:
            window = int(token)
            if window < 30:
                raise ValueError("Training windows shorter than 30 days are not supported")
        if window not in windows:
            windows.append(window)
    if not windows:
        raise ValueError("At least one training window is required")
    return tuple(windows)


def training_window_label(days: int | None) -> str:
    return "all_history" if days is None else f"{days}d"


def select_origins(
    flow: pd.DataFrame, config: BacktestConfig
) -> tuple[list[pd.Timestamp], pd.Timestamp]:
    """Return daily origins including a pre-evaluation calibration warm-up period."""
    latest = pd.Timestamp(flow["ds"].max()).floor("h")
    final_origin_date = (latest - pd.Timedelta(hours=config.horizon)).normalize()
    final_origin = final_origin_date + pd.Timedelta(hours=config.origin_hour)
    while final_origin + pd.Timedelta(hours=config.horizon) > latest:
        final_origin -= pd.Timedelta(days=1)

    score_start = (final_origin - pd.Timedelta(days=config.evaluation_days - 1)).normalize()
    score_start += pd.Timedelta(hours=config.origin_hour + 1)
    warmup_start = score_start - pd.Timedelta(days=config.calibration_days)
    first_origin = warmup_start.normalize() + pd.Timedelta(hours=config.origin_hour)

    origins = list(pd.date_range(first_origin, final_origin, freq="D"))
    if not origins:
        raise ValueError("No eligible anomaly backtest origins")
    return origins, score_start


def summarize_origin_coverage(flow: pd.DataFrame, config: BacktestConfig) -> pd.DataFrame:
    """Describe whether every target is truly available at each planned daily origin."""
    origins, score_start = select_origins(flow, config)
    records: list[dict[str, object]] = []
    for origin in origins:
        history = flow.loc[flow["ds"].le(origin)]
        for target in FLOW_TARGETS:
            valid = history.loc[history[target].notna(), "ds"]
            latest = pd.Timestamp(valid.max()) if not valid.empty else pd.NaT
            available = pd.notna(latest) and latest == origin
            gap_hours = (
                float((origin - latest) / pd.Timedelta(hours=1))
                if pd.notna(latest)
                else np.nan
            )
            records.append(
                {
                    "origin": origin,
                    "target": target,
                    "in_scored_period": origin + pd.Timedelta(hours=1) >= score_start,
                    "available_at_origin": bool(available),
                    "latest_available_at_or_before_origin": latest,
                    "gap_hours": gap_hours,
                }
            )
    return pd.DataFrame(records)


def _fit_prophet_forecast(
    history: pd.DataFrame,
    *,
    target: str,
    origin: pd.Timestamp,
    horizon: int,
) -> pd.DataFrame:
    """Fit the same vanilla Prophet control used by production and forecast one day."""
    from prophet import Prophet  # Lazy import keeps calibration unit tests lightweight.

    train = history[["ds", target]].dropna().rename(columns={target: "y"})
    if len(train) < 24 * 30:
        raise ValueError(f"Insufficient training rows for {target} at {origin}: {len(train)}")
    if pd.Timestamp(train["ds"].max()) != origin:
        raise ValueError(
            f"Training data for {target} does not end at origin {origin}; "
            f"latest={train['ds'].max()}"
        )

    model = Prophet(interval_width=0.95)
    model.fit(train)
    future = pd.DataFrame(
        {"ds": pd.date_range(origin + pd.Timedelta(hours=1), periods=horizon, freq="h")}
    )
    prediction = model.predict(future)
    return prediction[["ds", "yhat", "yhat_lower", "yhat_upper"]].copy()


def generate_predictions(
    flow: pd.DataFrame, config: BacktestConfig
) -> tuple[pd.DataFrame, pd.Timestamp]:
    """Generate one non-overlapping 24-hour forecast block from each daily origin."""
    origins, score_start = select_origins(flow, config)
    actuals = flow.set_index("ds")
    rows: list[pd.DataFrame] = []

    for window_days in config.training_windows:
        label = training_window_label(window_days)
        print(f"Anomaly backtest: training_window={label}, origins={len(origins)}")
        for origin_index, origin in enumerate(origins, start=1):
            if origin_index == 1 or origin_index % 14 == 0 or origin_index == len(origins):
                print(f"  origin {origin_index}/{len(origins)}: {origin}")

            history_start = flow["ds"].min()
            if window_days is not None:
                history_start = max(history_start, origin - pd.Timedelta(days=window_days))
            history = flow.loc[flow["ds"].between(history_start, origin)].copy()

            for target in FLOW_TARGETS:
                try:
                    forecast = _fit_prophet_forecast(
                        history, target=target, origin=origin, horizon=config.horizon
                    )
                except ValueError as exc:
                    print(f"  SKIP {label} {target} {origin}: {exc}")
                    continue

                forecast["actual"] = forecast["ds"].map(actuals[target])
                forecast["target"] = target
                forecast["training_window"] = label
                forecast["origin"] = origin
                forecast["horizon_hour"] = np.arange(1, len(forecast) + 1)
                rows.append(forecast)

    if not rows:
        raise RuntimeError("No anomaly backtest forecasts were generated")

    predictions = pd.concat(rows, ignore_index=True)
    predictions["actual"] = pd.to_numeric(predictions["actual"], errors="coerce")
    predictions = predictions.dropna(subset=["actual", "yhat", "yhat_upper"])
    predictions["residual"] = predictions["actual"] - predictions["yhat"]
    predictions["hour_of_week"] = (
        predictions["ds"].dt.dayofweek * 24 + predictions["ds"].dt.hour
    )
    return (
        predictions.sort_values(["training_window", "target", "ds"]).reset_index(drop=True),
        score_start,
    )


def _rolling_quantile(
    frame: pd.DataFrame,
    *,
    group_columns: list[str],
    value_column: str,
    quantile: float,
    calibration_days: int,
    min_samples: int,
) -> pd.Series:
    """Leakage-safe time-windowed residual quantile aligned to the original frame."""
    result = pd.Series(np.nan, index=frame.index, dtype=float)
    for _, group in frame.groupby(group_columns, sort=False):
        ordered = group.sort_values("ds")
        series = pd.Series(
            ordered[value_column].to_numpy(dtype=float),
            index=pd.DatetimeIndex(ordered["ds"]),
        )
        quantiles = series.rolling(
            f"{calibration_days}D",
            min_periods=min_samples,
            closed="left",
        ).quantile(quantile)
        result.loc[ordered.index] = quantiles.to_numpy()
    return result


def add_empirical_thresholds(
    predictions: pd.DataFrame,
    *,
    calibration_days: int,
    min_global_samples: int = 24 * 14,
    min_context_samples: int = 8,
) -> pd.DataFrame:
    """Add global and hour-of-week empirical upper thresholds using prior errors only."""
    out = predictions.copy().sort_values(["training_window", "target", "ds"])
    base_groups = ["training_window", "target"]

    out["residual_q95_global"] = _rolling_quantile(
        out,
        group_columns=base_groups,
        value_column="residual",
        quantile=0.95,
        calibration_days=calibration_days,
        min_samples=min_global_samples,
    )
    out["residual_q97_5_global"] = _rolling_quantile(
        out,
        group_columns=base_groups,
        value_column="residual",
        quantile=0.975,
        calibration_days=calibration_days,
        min_samples=min_global_samples,
    )
    out["residual_q99_global"] = _rolling_quantile(
        out,
        group_columns=base_groups,
        value_column="residual",
        quantile=0.99,
        calibration_days=calibration_days,
        min_samples=min_global_samples,
    )
    out["residual_q95_how"] = _rolling_quantile(
        out,
        group_columns=[*base_groups, "hour_of_week"],
        value_column="residual",
        quantile=0.95,
        calibration_days=calibration_days,
        min_samples=min_context_samples,
    )

    # Sparse hour-of-week cells deliberately fall back to the stable global estimate.
    contextual_q95 = out["residual_q95_how"].fillna(out["residual_q95_global"])
    out["empirical_upper_global_95"] = out["yhat"] + out["residual_q95_global"]
    out["empirical_upper_global_97_5"] = out["yhat"] + out["residual_q97_5_global"]
    out["empirical_upper_global_99"] = out["yhat"] + out["residual_q99_global"]
    out["empirical_upper_how_95"] = out["yhat"] + contextual_q95
    return out.sort_index()


def _episode_stats(timestamps: pd.Series) -> tuple[int, int, float]:
    stamps = pd.Series(pd.to_datetime(timestamps)).dropna().sort_values().drop_duplicates()
    if stamps.empty:
        return 0, 0, 0.0
    groups = stamps.diff().ne(pd.Timedelta(hours=1)).cumsum()
    lengths = stamps.groupby(groups).size()
    return int(len(lengths)), int(lengths.max()), float(lengths.mean())


def summarize_detectors(scored: pd.DataFrame) -> pd.DataFrame:
    """Summarize alert burden, persistence, and excursion magnitude by target."""
    records: list[dict[str, object]] = []
    for (window, target), group in scored.groupby(
        ["training_window", "target"], sort=True
    ):
        for detector, threshold_column in DETECTOR_THRESHOLDS.items():
            eligible = group.dropna(subset=["actual", threshold_column]).copy()
            if eligible.empty:
                continue
            eligible["alert"] = eligible["actual"].gt(eligible[threshold_column])
            alerts = eligible.loc[eligible["alert"]].copy()
            episodes, max_episode, mean_episode = _episode_stats(alerts["ds"])
            days = max(1, eligible["ds"].dt.date.nunique())
            excess = alerts["actual"] - alerts[threshold_column]

            records.append(
                {
                    "training_window": window,
                    "target": target,
                    "detector": detector,
                    "n_scored": int(len(eligible)),
                    "n_alerts": int(len(alerts)),
                    "upper_exceedance_rate": float(eligible["alert"].mean()),
                    "upper_coverage": float(1.0 - eligible["alert"].mean()),
                    "alerts_per_day": float(len(alerts) / days),
                    "episode_count": episodes,
                    "max_episode_hours": max_episode,
                    "mean_episode_hours": mean_episode,
                    "mean_alert_excess": float(excess.mean()) if len(excess) else 0.0,
                    "median_alert_excess": float(excess.median()) if len(excess) else 0.0,
                    "mae_expected_value": float(
                        (eligible["actual"] - eligible["yhat"]).abs().mean()
                    ),
                }
            )
    return pd.DataFrame(records)


def summarize_overall(by_target: pd.DataFrame) -> pd.DataFrame:
    if by_target.empty:
        return pd.DataFrame()
    records: list[dict[str, object]] = []
    for (window, detector), group in by_target.groupby(
        ["training_window", "detector"], sort=True
    ):
        weights = group["n_scored"].astype(float)
        total_scored = int(weights.sum())
        total_alerts = int(group["n_alerts"].sum())
        records.append(
            {
                "training_window": window,
                "detector": detector,
                "n_scored": total_scored,
                "n_alerts": total_alerts,
                "upper_exceedance_rate": (
                    float(total_alerts / total_scored) if total_scored else np.nan
                ),
                "weighted_alerts_per_day": float(
                    np.average(group["alerts_per_day"], weights=weights)
                ),
                "mean_max_episode_hours": float(
                    np.average(group["max_episode_hours"], weights=weights)
                ),
                "weighted_mae_expected_value": float(
                    np.average(group["mae_expected_value"], weights=weights)
                ),
            }
        )
    return pd.DataFrame(records)


def run_backtest(
    flow: pd.DataFrame, config: BacktestConfig
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    predictions, score_start = generate_predictions(flow, config)
    calibrated = add_empirical_thresholds(
        predictions,
        calibration_days=config.calibration_days,
        min_global_samples=config.min_global_samples,
        min_context_samples=config.min_context_samples,
    )
    scored = calibrated.loc[calibrated["ds"].ge(score_start)].copy()
    by_target = summarize_detectors(scored)
    overall = summarize_overall(by_target)
    return overall, by_target, scored


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--flow-url", default=FLOW_URL)
    parser.add_argument("--evaluation-days", type=int, default=180)
    parser.add_argument("--calibration-days", type=int, default=90)
    parser.add_argument(
        "--training-days",
        default="365",
        help="Comma-separated training windows in days; use 'all' for full history",
    )
    parser.add_argument("--origin-hour", type=int, default=6)
    parser.add_argument("--horizon", type=int, default=24)
    parser.add_argument("--min-global-samples", type=int, default=24 * 14)
    parser.add_argument("--min-context-samples", type=int, default=8)
    parser.add_argument(
        "--output-dir", type=Path, default=Path("validation/anomaly-backtest")
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    if not 0 <= args.origin_hour <= 23:
        raise ValueError("origin-hour must be between 0 and 23")
    if args.evaluation_days < 1 or args.calibration_days < 1:
        raise ValueError("evaluation-days and calibration-days must be positive")

    config = BacktestConfig(
        evaluation_days=args.evaluation_days,
        calibration_days=args.calibration_days,
        training_windows=parse_training_windows(args.training_days),
        origin_hour=args.origin_hour,
        horizon=args.horizon,
        min_global_samples=args.min_global_samples,
        min_context_samples=args.min_context_samples,
    )
    flow = load_flow(args.flow_url)
    origin_coverage = summarize_origin_coverage(flow, config)
    overall, by_target, scored = run_backtest(flow, config)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    overall_path = args.output_dir / "summary.csv"
    target_path = args.output_dir / "by_target.csv"
    predictions_path = args.output_dir / "scored_predictions.csv"
    coverage_path = args.output_dir / "origin_coverage.csv"
    overall.to_csv(overall_path, index=False)
    by_target.to_csv(target_path, index=False)
    scored.to_csv(predictions_path, index=False)
    origin_coverage.to_csv(coverage_path, index=False)

    print("\n=== Overall anomaly detector comparison ===")
    if overall.empty:
        print("No scored rows; increase the calibration/backtest history")
    else:
        print(overall.to_string(index=False))

    missing_origins = origin_coverage.loc[~origin_coverage["available_at_origin"]]
    print("\n=== Historical origin coverage ===")
    if missing_origins.empty:
        print("All planned target/origin combinations have data at the exact origin.")
    else:
        unique_origins = missing_origins["origin"].nunique()
        print(
            f"Missing exact-origin data for {len(missing_origins)} target/origin "
            f"combinations across {unique_origins} origin(s)."
        )
        print(missing_origins.to_string(index=False))

    print(f"\nWrote {overall_path}")
    print(f"Wrote {target_path}")
    print(f"Wrote {predictions_path}")
    print(f"Wrote {coverage_path}")


if __name__ == "__main__":
    main()
